name: CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Run Node.js tests
              run: npm test

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.16

            - name: Run Go tests
              run: go test ./...

            - name: Lint Go code
              run: golangci-lint run

            - name: Run Signin Tests
              run: go test ./auth/signin_test.go

            - name: Run Signup Tests
              run: go test ./auth/signup_test.go